import { Router } from "express";
import ProductManager from '../ProductManager.js';
const productManager = new ProductManager();

const router = Router();

router.get('/', async (req, res) => {
    const limit = req.query.limit;
    const products = await productManager.getProducts();

    if(limit){
        return res.send(products.splice(0, limit));
    }

    res.send(products);
});

router.get('/search/:productCode', async (req, res) => {
    const productCode = req.params.productCode;
    const productSearched = await productManager.getProductByCode(productCode);
    if(productSearched === undefined){
        return res.status(404).send();
    }

    res.send(productSearched);
});
// You can get the product by its code (for example "abc123")

router.get('/:productId', async (req, res) => {
    const productId = req.params.productId;
    const productSearched = await productManager.getProductById(parseInt(productId, 10));
    if(productSearched === undefined){
        return res.status(404).send();
    }

    res.send(productSearched);
});
// Or you can get the product by its id (for example 1)

router.post('/', async (req, res) => {
    const title = req.body.title;
    const description = req.body.description;
    const price = req.body.price;
    const stock = req.body.stock;
    const category = req.body.category;
    await productManager.addProduct(title, description, price, stock, category);
    if(title === undefined || description === undefined || price === undefined || stock === undefined || category === undefined){
        return res.status(400);
    }
    res.send();
});

/* If the array in Products.json file is empty, try posting this product using Thunder Client or POSTMAN
with this url: http://localhost:8080/api/products
{
    "title": "Shorts negros",
    "description": "Talle M - L - XL",
    "price": 7000,
    "stock": 45,
    "category": "1"
} */

//You cannot post two products with the same title, the code and id get autogenerated (you won´t get two products with the same code or id)

router.put('/:productId', async (req, res) => {
    const productId = req.params.productId;
    const productProp = req.body.productProp;
    const change = req.body.change;
    await productManager.updateProduct(parseInt(productId, 10), productProp, change);
    if(productId === undefined || productProp === undefined || change === undefined){
        return res.status(400);
    }
    res.send();
});

/* If the array in Products.json file has, for example, a product with id 1, try updating the product
with this url: http://localhost:8080/api/products/1
{
    "productProp": "price",
    "change": 9000
} */

router.delete('/:productId', async (req, res) => {
    const productId = req.params.productId;
    await productManager.deleteProduct(parseInt(productId, 10));
    if(productId === undefined){
        return res.status(404).send();
    }
    res.send();
});

export default router;